--- 
name: sample_app
extensions: 
- json
- another-extension
bbver: 4.6
wp: 
  productid: 2d178270-3b50-012f-047e-000c29ea8393
android: 
  version: 2.1
sdk: /home/spritle/.rvm/gems/ruby-1.8.7-p352/gems/rhodes-3.3.1
build: debug
applog: rholog.txt
version: 1.0
symbian: 
  uid: 3782597594
sdkversion: 3.3.0
vendor: rhomobile
iphone: 
  provisionprofile: 
  BundleURLScheme: sampleapp
  BundleIdentifier: com.rhomobile.sampleapp
  sdk: iphonesimulator5.0
  codesignidentity: 
  entitlements: 
  configuration: Release
